name: Staging CI
on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "16.16.0"
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
          

