name: Staging CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "16.16.0"
      - run: npm install
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Create Release
        if: github.event_name == 'push'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/boilerplate_node:latest
      # - name: Build Image
      #   if: github.event_name == 'push'
      #   run: npm start  
      # - name: Deploy to Staging
      #   if: github.event_name == 'push'
      #   run: npm start

