name: Staging CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "16.16.0"
      - run: npm install
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Create Release
        if: github.event_name == 'push'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      # - name: Build Image
      #   if: github.event_name == 'push'
      #   run: npm start  
      # - name: Deploy to Staging
      #   if: github.event_name == 'push'
      #   run: npm start

